### ISSUE TITLE
Is there a way to swap tsserver and deno lsp per project?

### ISSUE THREAD

**Issue by npearson72** [fannheyward/coc-deno#191]
Perhaps a flag in the root directory?

**Comment by fannheyward** [comment]
Yes, after you did `deno.initializeWorkspace` command, coc-deno will enable deno and disable tsserver, and save the settings to `.vim/coc-settings.json` in your project.

```json
{
  "deno.enable": true,
  "tsserver.enable": false
}
```

You can change the settings to swap the two LS.

**Comment by npearson72** [comment]
Thanks @fannheyward, but I wasn't able to get that command working. I get the following error:

```
[coc.nvim]: Unable to locate workspace folder configuration for file:///Users/nathan/Dev/learning/deno
Unable to locate workspace folder configuration for file:///Users/nathan/Dev/learning/deno
Unable to locate workspace folder configuration for file:///Users/nathan/Dev/learning/deno
Unable to locate workspace folder configuration for file:///Users/nathan/Dev/learning/deno
```

Any ideas?

**Comment by fannheyward** [comment]
What's your `:CocInfo`? Looks like your coc.nvim is outdated, upgrade your coc.nvim and try again.

**Comment by npearson72** [comment]
Seems updated, but am seeing an error when I run `CocInfo`. I also use `adsf` to manage deno (not sure if that matters)?

```
## versions

vim version: NVIM v0.8.0
node version: v16.17.1
coc.nvim version: 0.0.82-75f2b7eb 2022-12-06 00:50:36 +0800
coc.nvim directory: /Users/nathan/.config/nvim/plugged/coc.nvim
term: tmux
platform: darwin

## Log of coc.nvim

2022-12-10T19:28:17.114 INFO (pid:30373) [extension:coc-git] - Looking for git in: git
2022-12-10T19:28:17.273 INFO (pid:30373) [plugin] - coc.nvim initialized with node: v16.17.1 after 316
2022-12-10T19:28:19.137 INFO (pid:30373) [attach] - receive notification: runCommand [ 'deno.initializeWorkspace' ]
2022-12-10T19:28:19.160 INFO (pid:30373) [language-client-index] - Language server "deno" started with 30512
2022-12-10T19:28:20.853 ERROR (pid:30373) [configurations] - Unable to locate workspace folder configuration file:///Users/nathan/Dev/learning/deno Error
    at Object.update (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:152:6784)
    at doInitialize (/Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2448:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2459:5
    at async xk.fireCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:69:4089)
    at async bm.runCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:261:24114)
    at async Ym.cocAction (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:47116)
    at async RD.<anonymous> (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:48848)
2022-12-10T19:28:20.853 ERROR (pid:30373) [configurations] - Unable to locate workspace folder configuration file:///Users/nathan/Dev/learning/deno Error
    at Object.update (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:152:6784)
    at doInitialize (/Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2449:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2459:5
    at async xk.fireCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:69:4089)
    at async bm.runCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:261:24114)
    at async Ym.cocAction (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:47116)
    at async RD.<anonymous> (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:48848)
2022-12-10T19:28:20.854 ERROR (pid:30373) [configurations] - Unable to locate workspace folder configuration file:///Users/nathan/Dev/learning/deno Error
    at Object.update (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:152:6784)
    at doInitialize (/Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2450:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2459:5
    at async xk.fireCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:69:4089)
    at async bm.runCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:261:24114)
    at async Ym.cocAction (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:47116)
    at async RD.<anonymous> (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:48848)
2022-12-10T19:28:20.854 ERROR (pid:30373) [configurations] - Unable to locate workspace folder configuration file:///Users/nathan/Dev/learning/deno Error
    at Object.update (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:152:6784)
    at doInitialize (/Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2453:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /Users/nathan/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2459:5
    at async xk.fireCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:69:4089)
    at async bm.runCommand (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:261:24114)
    at async Ym.cocAction (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:47116)
    at async RD.<anonymous> (/Users/nathan/.config/nvim/plugged/coc.nvim/build/index.js:281:48848)
2022-12-10T19:28:20.856 INFO (pid:30373) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_coc_helper_1',
  'BufWipeout',
  2
]
2022-12-10T19:28:20.857 INFO (pid:30373) [attach] - receive notification: runCommand [
  'coc-helper.internal.didVimEvent_m1_v0_15_2_explorer_2',
  'BufWipeout',
  2
]
2022-12-10T19:28:24.428 INFO (pid:30373) [attach] - receive notification: showInfo []

```
<img width="417" alt="Screen Shot 2022-12-10 at 7 29 09 PM" src="https://user-images.githubusercontent.com/1323414/206883617-1e8af530-1875-474b-9d91-2a55a6acba7c.png">

**Comment by fannheyward** [comment]
Will check this ASAP.

**Comment by fannheyward** [comment]
Do you have something like `.git` in your `/Users/nathan/Dev/learning/deno`, seems like coc.nvim can't resolve the root of the project.

**Comment by fannheyward** [comment]
The error is came from coc.nvim that can't resolve and find configuration folder. Try `mkdir .vim` in your project.

I can't reproduce this error.

https://github.com/neoclide/coc.nvim/blob/9386771d41ad151d7e49fa4c2357f20c8fe1c14d/src/configuration/index.ts#L322-L323

**Comment by npearson72** [comment]
Hmm, so I added the following to my main `~/.config/nvim/coc-settings.json` file:

```
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": false,
  "tsserver.enable": false
```

Then in a random empty directory, I opened up nvim and ran: `CocCommand deno.initializeWorkspace`. That produced a `<some-project-directory>/.vim/~coc-settings.json` file. In it are these values:

```
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "prettier.disableLanguages": [
    "typescript",
    "javascript"
  ],
  "tsserver.enable": false
}
```

However, it still seems to be referring to `tsserver`:

<img width="746" alt="Screen Shot 2022-12-10 at 10 52 13 PM" src="https://user-images.githubusercontent.com/1323414/206888604-a17a3c0e-08ec-4b0c-b27b-82a6684b9ea0.png">

Is there some flag I need in my main coc settings to allow a local override?

**Comment by npearson72** [comment]
Hi @fannheyward, I just wanted to update you. I think my issue was that I was symlinking my main `coc-settings.json` file from my `~/.dots` directory.

After setting `g:coc_config_home` everything began working normally.

Thank you for looking into this. I'm closing the issue now.
