### ISSUE TITLE
Extension activation/deactivation support stopped working with coc.nvim 0.0.82

### ISSUE THREAD

**Issue by filmaj** [fannheyward/coc-deno#208]
Hello! Thanks for the great project. I have used it a lot 🙇 🙏 

I have a question.. I recently upgraded from coc.nvim 0.0.80 to 0.0.82, and a customization from my `.vimrc` stopped working in coc-deno as a result.

In short, the customization sorts out when to enable coc-deno and when to enable coc-tsserver. That is, to figure out if a project is a deno project, or a node/other TypeScript project.

The reason I upgraded to coc.nvim 0.0.82 is because the latest version of coc-tsserver requires this as a minimum version 😞 

Here is the code for the customization:

```
function! s:enable_extensions_for_deno()
  call CocActionAsync('activeExtension', 'coc-deno')
  call CocActionAsync('deactivateExtension', 'coc-tsserver')
endfunction
function! s:enable_extensions_for_node()
  call CocActionAsync('activeExtension', 'coc-tsserver')
  call CocActionAsync('deactivateExtension', 'coc-deno')
endfunction
function! s:set_ts_lsp()
  " enable/disable coc-tsserver/coc-deno based on detection of diff ecma runtimes
  let l:bufname = expand('%')
  " The buffer is deno lsp virtual file
  if l:bufname =~# '^deno:/'
    call s:enable_extensions_for_deno()
    return
  endif
  let l:path = empty(l:bufname) ? '.' : expand('%:p:h')
  if !empty(finddir('node_modules', l:path . ';')) || !empty(findfile('package.json', l:path . ';'))
    call s:enable_extensions_for_node()
    return
  endif
  if !empty(findfile('deno.jsonc', l:path . ';')) || !empty(findfile('import_map.json', l:path . ';'))
    call s:enable_extensions_for_deno()
    return
  endif
  " TODO: check for existence of .vim/coc-settings.json and look for
  " deno.enable and/or tsserver.enable config props
endfunction
" figure out whether to enable deno or tsserver LSP
autocmd filetype javascript,typescript call s:set_ts_lsp()
```

However, since upgrading to coc.nvim 0.0.82, I see the following in my `:messages` after loading up a deno project in vim:

```
[coc.nvim] Error on activate extension coc-deno: import_coc3.services.registerLanguageClient is not a function
[coc.nvim] Error on notification "activeExtension": TypeError: import_coc3.services.registerLanguageClient is not a
function
[coc.nvim] Error on notification "activeExtension": TypeError: import_coc3.services.registerLanguageClient is not a
function
```

Not sure if this is the correct place to file the issue or ask for help.. in any case, any insight is appreciated! Maybe also I'm trying to solve the problem of activating/deactivating the different coc extensions in a funny way.. not sure, it's worked so far 🤷 but if other people have different suggestions on how to solve this issue, I would love to hear them!

Thank you 🙏

**Comment by fannheyward** [comment]
> services.registerLanguageClient

What's your `:CocInfo`? Looks like you're not using the _latest_ coc.nvim release. 

>  the customization sorts out when to enable coc-deno and when to enable coc-tsserver

Got your point and problem. In coc-deno, there's a command `deno.initializeWorkspace`, to enable coc-deno and disable coc-tsserver for your project, and save the settings in your project's `.vim/coc-settings.json`, as local configurations, this means you don't need to activation/deactivation extensions anymore.

**Comment by filmaj** [comment]
Thanks for your comment! That's really nice to know I don't need to switch between the two LSP manually in my vimrc :) I will instead use the `.vim/coc-settings.json` whenever possible. It seems like I can enable each LSP individually in this file, so for non-deno projects, I will try to use this file to get it to work.

So I have removed my custom vimrc LSP-switching code that I posted in the original comment. I still get a similar error, however: 

```
## versions

vim version: VIM - Vi IMproved 9.0 9001550
node version: v20.2.0
coc.nvim version: 0.0.82-7a50d4d9 2022-08-01 01:37:29 +0800
coc.nvim directory: /Users/fmaj/src/dotfiles/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-06-21T09:02:10.322 INFO (pid:40573) [configurations] - Add folder configuration from cwd: /Users/fmaj/src/deno-slack-sdk/.vim/coc-settings.json
2023-06-21T09:02:10.325 INFO (pid:40573) [configurations] - Change folder configuration from cwd to: /Users/fmaj/src/deno-slack-sdk/.vim/coc-settings.json
2023-06-21T09:02:10.514 INFO (pid:40573) [services] - registered service "eslint"
2023-06-21T09:02:10.514 INFO (pid:40573) [services] - ESLint state change: stopped => starting
2023-06-21T09:02:10.552 INFO (pid:40573) [services] - registered service "tsserver"
2023-06-21T09:02:10.576 INFO (pid:40573) [plugin] - coc.nvim initialized with node: v20.2.0 after 169ms
2023-06-21T09:02:10.577 ERROR (pid:40573) [extensions] - Error on active extension coc-deno: import_coc3.services.registerLanguageClient is not a function TypeError: import_coc3.services.registerLanguageClient is not a function
    at tryActivate (/Users/fmaj/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2727:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.activate (/Users/fmaj/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2789:3)
2023-06-21T09:02:10.623 INFO (pid:40573) [core-watchman] - watchman watching project: /Users/fmaj/src/deno-slack-sdk
2023-06-21T09:02:10.696 INFO (pid:40573) [services] - ESLint state change: starting => running
2023-06-21T09:02:10.700 INFO (pid:40573) [services] - service eslint started
2023-06-21T09:02:15.627 INFO (pid:40573) [attach] - receive notification: showInfo []
```

In a separate node project, with no `.vim/coc-settings.json` file (but it does have a `.vscode/settings.json` file), there doesn't seem to be an issue and coc-tsserver loads fine, and here is what `:CocInfo` says:

```
## versions

vim version: VIM - Vi IMproved 9.0 9001550
node version: v20.2.0
coc.nvim version: 0.0.82-7a50d4d9 2022-08-01 01:37:29 +0800
coc.nvim directory: /Users/fmaj/src/dotfiles/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-06-21T09:22:15.019 INFO (pid:52721) [services] - registered service "eslint"
2023-06-21T09:22:15.023 INFO (pid:52721) [services] - ESLint state change: stopped => starting
2023-06-21T09:22:15.059 INFO (pid:52721) [services] - registered service "tsserver"
2023-06-21T09:22:15.063 INFO (pid:52721) [plugin] - coc.nvim initialized with node: v20.2.0 after 177ms
2023-06-21T09:22:15.092 INFO (pid:52721) [services] - service tsserver started
2023-06-21T09:22:15.135 INFO (pid:52721) [core-watchman] - watchman watching project: /Users/fmaj/src/bolt-js
2023-06-21T09:22:15.252 INFO (pid:52721) [services] - ESLint state change: starting => running
2023-06-21T09:22:15.256 INFO (pid:52721) [services] - service eslint started
2023-06-21T09:22:18.450 INFO (pid:52721) [attach] - receive notification: showInfo []
```

(P.S. given what you've shown me with the `coc-settings.json` file, it seems I can also disable the coc-eslint extension using the same technique within deno projects!)

**Comment by filmaj** [comment]
I set `"eslint.enable": false` in my deno project now to clean up the output of `:CocInfo` a bit more in this project, so here it is now:

```
## versions

vim version: VIM - Vi IMproved 9.0 9001550
node version: v20.2.0
coc.nvim version: 0.0.82-7a50d4d9 2022-08-01 01:37:29 +0800
coc.nvim directory: /Users/fmaj/src/dotfiles/.vim/bundle/coc.nvim
term: iTerm.app
platform: darwin

## Log of coc.nvim

2023-06-21T09:31:10.648 INFO (pid:58340) [configurations] - Add folder configuration from cwd: /Users/fmaj/src/deno-slack-sdk/.vim/coc-settings.json
2023-06-21T09:31:10.651 INFO (pid:58340) [configurations] - Change folder configuration from cwd to: /Users/fmaj/src/deno-slack-sdk/.vim/coc-settings.json
2023-06-21T09:31:10.877 INFO (pid:58340) [services] - registered service "tsserver"
2023-06-21T09:31:10.885 INFO (pid:58340) [plugin] - coc.nvim initialized with node: v20.2.0 after 152ms
2023-06-21T09:31:10.885 ERROR (pid:58340) [extensions] - Error on active extension coc-deno: import_coc3.services.registerLanguageClient is not a function TypeError: import_coc3.services.registerLanguageClient is not a function
    at tryActivate (/Users/fmaj/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2727:51)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.activate (/Users/fmaj/.config/coc/extensions/node_modules/coc-deno/lib/index.js:2789:3)
2023-06-21T09:31:10.942 INFO (pid:58340) [core-watchman] - watchman watching project: /Users/fmaj/src/deno-slack-sdk
2023-06-21T09:31:12.527 INFO (pid:58340) [attach] - receive notification: highlight []
2023-06-21T09:31:14.688 INFO (pid:58340) [attach] - receive notification: showInfo []
```

**Comment by yaegassy** [comment]
Hi, @filmaj 

It appears that an error is occurring that you are concerned about. (`TypeError: import_coc3.services.registerLanguageClient...`)

Will using the latest version from the `master` branch of the repository instead of coc.nvim v0.0.82 solve your issue? To use the `master` branch, please refer to the relevant section in the README. <https://github.com/neoclide/coc.nvim#quick-start>

**Comment by fannheyward** [comment]
I'll change coc-deno to make it work with tag release.

**Comment by filmaj** [comment]
Using the release branch fixed it - thank you!
